### Rate a day
POST http://localhost:8080/day/
Content-Type: application/json

{
  "day": "2026-07-07",
  "score": 2
}

### Get by day
GET http://localhost:8080/day/?from=2026-07-06&to=2026-07-09

### Get by day
GET http://localhost:8080/day/?from=2026-07-07
