### Rate a day
POST http://localhost:8080/day/
Content-Type: application/json

{
  "day": "2025-07-24",
  "score": 1
}

### Get by day
GET http://localhost:8080/day/?from=2021-07-06&to=2025-12-09

### Get by day
GET http://localhost:8080/day/?from=2026-07-20
