### Rate a day
POST http://localhost:8080/day/
Content-Type: application/json

{
  "day": "2026-07-06",
  "score": 4
}

### Get today
GET http://localhost:8080/day/today

### Get by day
GET http://localhost:8080/day/2026-06-23
